cropper:
  cropR: 0.08
  cropR2: 0.08
  cropZ: 0
  ladC: 100000
  ladW: 0
  ladW2: 30000
  mesh: 0.001
  nfmin: 0
  nfrad: 0.005
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.8
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
  pshift_genpc:
    paramsetN: 1
    projector:
      Intensity: 120
searcher:
  distance_threshold: 1.5
  feature_mesh: 0.004
  feature_radius: 5.0
  icp_threshold: 5.0
  normal_min_nn: 0
  normal_radius: 2.0
  repeat: 5
  rotate: 0
