cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 30000
  ladW2: 30000
  mesh: 2
  nfmin: 20
  nfrad: 5
picker:
  azimuth:
    max: 180
    min: 0
  fitness:
    max: 1
    min: 0
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
  pshift_genpc:
    paramsetN: 1
    projector:
      Intensity: 120
  ycam:
    ExposureTimeLevel: 4
    projector:
      Intensity: 255
searcher:
  cutter:
    base: -97
    distance: 500
    offset: 180
    width: 5
  distance_threshold: 100
  feature_mesh: 4
  feature_radius: 18
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 8
  repeat: 1
  rotate: 0
