cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 0
  ladW2: 30000
  mesh: 1
  nfmin: 10
  nfrad: 5
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.66
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
  pshift_genpc:
    paramsetN: 1
    projector:
      Intensity: 120
  ycam:
    ExposureTimeLevel: 4
    projector:
      Intensity: 255
searcher:
  cutter:
    base: -97
    offset: 180
    width: 2.5
  distance_threshold: 20
  feature_mesh: 2
  feature_radius: 7
  icp_threshold: 1
  normal_min_nn: 0
  normal_radius: 5
  repeat: 2
  rotate: 2
