cropper:
  cropR: 0
  cropZ: 0
  ladC: 0
  ladW: 0
  mesh: 1
  nfmin: 0
  nfrad: 5
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.7
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
      Gain: 50
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intensity: 80
      Mode: 1
searcher:
  distance_threshold: 20
  feature_mesh: 3
  feature_radius: 7
  icp_threshold: 1
  normal_min_nn: 5
  normal_radius: 4
  repeat: 5
  rotate: 3
