config:
  searcher0:
    proc: 0
    solver: "ransac_solver"
    scenes: ["surface"]
    scene_frame_id: ["camera/capture0"]
    master_frame_id: ["camera/master0"]
    solve_frame_id: "camera/capture0"
  searcher1:
    proc: 1
    solver: "zhou_solver"
    scenes: ["surface"]
    scene_frame_id: ["camera/capture0"]
    master_frame_id: ["camera/master0"]
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/rovi/X1"
    ansback: "/rovi/Y1"
  picker:
    multiplex: 1
    solve_frame_id: "camera/capture0"
  report:
    "altitude": -25
    "rows": 4
    recipe: /dashboard/recipe
    keys: ["fitness","rmse","azimuth","rotation","Tx","Ty","Tz","tfeat","tmatch"]
    labels: ["Fitness","RMSE","Azimuth","Rotation","Shift X","Shift Y","Shift Z","Tfeat","Tmatch"]
  rsocket:
    base_frame_id: base
    source_frame_id: camera/master0
    target_frame_id: camera/capture0/solve0
