config:
  searcher0:
    proc: 0
    solver: "ransac_solver"
    scenes: ["surface"]
    scene_frame_ids: ["camera/capture0"]
    master_frame_ids: ["camera/master0"]
    solve_frame_id: "camera/capture0"
  searcher1:
    proc: 1
    solver: "zhou_solver"
    scenes: ["surface"]
    scene_frame_ids: ["camera/capture0"]
    master_frame_ids: ["camera/master0"]
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/rovi/X1"
    ansback: "/rovi/Y1"
  picker:
    multiplex: 1
    solve_frame_id: "camera/capture0"
  report:
    "altitude": -25
    "width": 1920
    "rows": 4
    recipe: /dashboard/recipe
    keys: ["pcount","fitness","rmse","azimuth","rotation","Tx","Ty","Tz","tcap","tfeat","tmatch","mean","stddev","median","mode"]
    labels: ["Points","Fitness","RMSE","Azimuth","Rotation","Shift X","Shift Y","Shift Z","Tcap","Tfeat","Tmatch","Mean","Stddev","Median","Mode"]
  rsocket:
    base_frame_id: base
    source_frame_id: camera/master0
    target_frame_id: camera/capture0/solve0
    update_frame_id: tool0_controller

