cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 6000
  ladW2: 30000
  mesh: 0.5
  nfmin: 0
  nfrad: 0
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.7
  rmse:
    max: 5
    min: 0
rovi:
  live:
    paramsetN: 1
  pshift_genpc:
    paramsetN: 1
searcher:
  distance_threshold: 1
  feature_mesh: 1
  feature_radius: 3
  icp_threshold: 0.5
  normal_min_nn: 0
  normal_radius: 3
  repeat: 5
  rotate: 0
