cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 0
  ladW2: 30000
  mesh: 0.5
  nfmin: 20
  nfrad: 5
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.85
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 30000
  pshift_genpc:
    paramsetN: 1
    projector:
      Intensity: 120
searcher:
  distance_threshold: 2
  feature_mesh: 4
  feature_radius: 5
  icp_threshold: 0.5
  normal_min_nn: 0
  normal_radius: 2
  repeat: 5
  rotate: 0
